### ISSUE TITLE
Features - Database

### ISSUE THREAD

**Issue by at-vietpham** [AT-PHPIntership/borrow-book#1]
@at-nale @at-haytran @at-haphan
Mọi người cập nhật Requiment và Database vào issue này như hôm qua anh có nói.

**Comment by at-haytran** [comment]
![diagramlibrary](https://user-images.githubusercontent.com/37792104/39854241-0f385272-5451-11e8-9a04-231ad35ec486.png)

**Comment by at-haytran** [comment]
##List Function
1.User        
    *Profile 
        *login, logout
        *register
        *update profile
    *Library 
        *Show book new
        *View list of all book
        *Show detail book
        *Search book by filters category
        *Search book by filters rate
        *Search book by filters language
        *Search book by filters number of page
        *Search book in text field
    *Post    
        **Add post
        **Update post
        **Delete post
        **Add rate
        **Update rate
    *Borrowes    
        *Show list borrow book of me
    *Favorite    
        *Mark favorite
    *
2.Admin       
    *Manage user     
        *View, Delete,Add,Update user
        *Search User
    *Manage Book 
        *Show book
        *Add book
        *Update book
        *Delete book
        *Search book
    *Manage Borrow   
        *Show list user borrow book
    *Manage post Show post
        *Delete post
        *Add post
    *Manage favorite 
        *Show all user favorite with book
    *Statistical

**Comment by at-haytran** [comment]
## List Function
1.User        
    * Profile 
        * login, logout
        * register
        * update profile
    * Library 
        * Show book new
        * View list of all book
        * Show detail book
        * Search book by filters category
        * Search book by filters rate
        * Search book by filters language
        * Search book by filters number of page
        * Search book in text field
    * Post    
        * Add post
        * Update post
        * Delete post
        * Add rate
        * Update rate
    * Borrowes    
        * Show list borrow book of me
    * Favorite    
        * Mark favorite
    * 
2.Admin       
    * Manage user     
        * View, Delete,Add,Update user
        * Search User
    * Manage Book 
        * Show book
        * Add book
        * Update book
        * Delete book
        * Search book
    * Manage Borrow   
        * Show list user borrow book
    * Manage post Show post
        * Delete post
        * Add post
    * Manage favorite 
        * Show all user favorite with book
    * Statistical

**Comment by at-haytran** [comment]
## List Function
1.User        
    * Profile 
        * login, logout
        * register
        * update profile

**Comment by at-haytran** [comment]
## List Function
1.User        
* Profile 
    * login, logout
    * register
    * update profile
* Library 
    * Show book new
    * View list of all book
    * Show detail book
    * Search book by filters category
    * Search book by filters rate
    * Search book by filters language
    * Search book by filters number of page
    * Search book in text field
* Post    
    * Add post
    * Update post
    * Delete post
    * Add rate
    * Update rate
* Borrowes    
    * Show list borrow book of me
* Favorite    
    * Mark favorite
2.Admin       
* Manage user     
    * View, Delete,Add,Update user
    * Search User
* Manage Book 
    * Show book
    * Add book
    * Update book
    * Delete book
    * Search book
* Manage Borrow   
    * Show list user borrow book
* Manage post Show post
    * Delete post
    * Add post
* Manage favorite 
    * Show all user favorite with book
* Statistical

**Comment by at-haytran** [comment]
Em xin cập nhật lại database vừa mới update.
![diagramlibrary](https://user-images.githubusercontent.com/37792104/39904086-709a5466-5500-11e8-87af-5a59ae135534.png)

**Comment by at-huydq** [comment]
LGTM
